### ISSUE TITLE
Hive name my be decoded incorrect in some corrupt hives

### ISSUE THREAD

**Issue by williballenthin** [williballenthin/python-registry#36]
via  @EricZimmerman...

    not all value names are stored as ascii, some are unicode.
    strange thing is i see what looks like ascii in some of the Unicode flagged ones. namepresent == 0 but its ascii for 'Letter' vs some crazy Chinese symbols

suggested logic:;

            if (NameLength == 0)
            {
                ValueName = "(default)";
            }
            else
            {
                if (NamePresentFlag > 0)
                {
                    ValueName = Encoding.ASCII.GetString(rawBytes, 0x18, NameLength);
                }
                else
                {
                    // in very rare cases, the valuename is in ascii even when it should be in Unicode.
                    var valString = BitConverter.ToString(rawBytes,0x18,NameLength);

                   bool foundMatch = false;
                    try {
                     foundMatch = Regex.IsMatch(valString, "-[!^0]{2}");
                    } catch (ArgumentException ex) {
                     // Syntax error in the regular expression
                    }

                    if (foundMatch)
                    {
                        // we found what appears to be unicode
                        ValueName = Encoding.Unicode.GetString(rawBytes, 0x18, NameLength);
                    }
                    else
                    {
                        ValueName = Encoding.ASCII.GetString(rawBytes, 0x18, NameLength);
                    }

                }
            }

**Comment by EricZimmerman** [comment]
my code is for use in vk records. i dont think it works that way in the header for the file name tho. it should always be unicode that i have seen
