### ISSUE TITLE
[Feature Request] RegistryKey should have to .reg format support

### ISSUE THREAD

**Issue by williballenthin** [williballenthin/python-registry#4]
The .reg format is the format used by Regedit and other tools when  Windows Registry keys are exported.  You can see an example here: http://www.byalexv.co.uk/RegFormat.html .   It would be nice to have a reg_format() method for the RegistryKey class which returns a string containing the corresponding .reg format content.

A compare_to(.reg_format_string) method may also be useful, although maybe not as appropriate in the core class.

**Comment by NiKiZe** [comment]
reg_export exists in samples, might be useful to import the export function to a separate class.
It does not support recursive export, but that is a trivial fix.

**Comment by williballenthin** [comment]
Thinking back to this issue, I don't think we should put the `.export()` method on the `RegistryValue`, but instead keep it in an external class/method. Doesn't make sense to mix up the responsibilities of being a data structure and formatting to text. `reg_export` is pretty good, though like you said, not recursive. You're welcome to add recursion, or I'll add it when I find I need it sometime ;-).

**Comment by williballenthin** [comment]
I'm going to close this issue as I think `reg_export` is pretty much what I had in mind. If anyone needs recursive support, open an issue, and I'll put that together right away!
