### ISSUE TITLE
Ability to pass a registry hive without a .read()

### ISSUE THREAD

**Issue by hiddenillusion** [williballenthin/python-registry#59]
The `Registry` class currently looks for a **filelikeobject** with a .read() and if that fails, assumes it's a string to the path of the file (which is then attempted to be opened with a .read() as well). 

It'd be useful to have the ability to pass the contents of a registry hive to the `Registry` class. 

e.g. - within pytsk, one would open a registry hive with something like this:

```
file_obj = filesystem_obj.open("/Windows/System32/Config/SYSTEM")
file_data = file_obj.read_random(0,file_obj.info.meta.size)
```

that produces:
```
HiWilli@hehe:~$ python test.py evidence.E01 | xxd
0000000: 7265 6766 eb02 0000 eb02 0000 59ec 2d6a  regf........Y.-j
0000010: 3515 d001 0100 0000 0500 0000 0000 0000  5...............
0000020: 0100 0000 2000 0000 00b0 9d00 0100 0000  .... ...........
0000030: 5300 5900 5300 5400 4500 4d00 0000 0000  S.Y.S.T.E.M.....
...
```

and this obviously isn't a **filelikeobject** so there's no read() which produces a TypeError "_file() argument 1 must be encoded string without NULL bytes, not str_"

My initial thought/work around is to add [another try statement](https://github.com/williballenthin/python-registry/blob/master/Registry/Registry.py#L314) along the lines of:
```python
      try:
            self._buf = filelikeobject.read()
        except AttributeError:
            try:
              with open(filelikeobject, "rb") as f:
                  self._buf = f.read()
            except TypeError:
                  self._buf = filelikeobject
        self._regf = RegistryParse.REGFBlock(self._buf, 0, False)
```

Not sure how often this comes up but figured I'd see your thoughts on it. I saw others doing workarounds like [here](https://github.com/dlcowen/dfirwizard/blob/64b27c1d691ef2ab171439540bec9d90988b78d4/usbdftsk.py#L140) where they write the registry hive to disk then read it, but seems like an unneeded step.

**Comment by zweger** [comment]
Can't you just use something like [StringIO](https://docs.python.org/2/library/stringio.html) instead?

**Comment by hiddenillusion** [comment]
@zweger I attempted StringIO initially as a workaround but that resulted in:

The StringIO instance itself had a read()

```python
file_obj = filesystem_obj.open("/Windows/System32/Config/SYSTEM")
file_data = file_obj.read_random(0,file_obj.info.meta.size)
file_data = StringIO.StringIO()
file_data.write(file_data)
#hasattr(file_data, 'read') = True
registry = Registry.Registry(file_data)
print(registry.hive_name())
```

but StringIO's read() seems to behave differently than you'd expect from a read() on a file-like object since that StringIO instance to `Registry` resulted in a `RegistryParse` error because [`self._buf`](https://github.com/williballenthin/python-registry/blob/master/Registry/Registry.py#L315) ends up having a len of 0.

Test | Result
--- | ---
print type(file_data) | type 'instance'
print hasattr(file_data, 'read') | True
print len(file_data.read()) | 0
print len(file_data.getvalue()) | 10485760

If I pass in the raw registry hive via **getvalue()** of the StringIO instance, which holds the data we'd expect a file-like object to contain during a read():

```python
file_obj = filesystem_obj.open("/Windows/System32/Config/SYSTEM")
file_data = file_obj.read_random(0,file_obj.info.meta.size)
file_data = StringIO.StringIO()
file_data.write(file_data)
reg = Registry.Registry(file_data.getvalue()) #no read()
print(registry.hive_name())
```
then I get the _TypeError_ mentioned above in `Registry` since it doesn't have read():

```TypeError: file() argument 1 must be encoded string without NULL bytes, not str```

perhaps I missed something or foo'bared somewhere - did you get different results?

**Comment by NiKiZe** [comment]
What about creating a dummy class that implements read?
```Python
class FileLikeDummy:
    def __init__(self, buf):
        self._buf = buf

    def read(self):
        return self._buf


# Based on previous code, untested
file_obj = filesystem_obj.open("/Windows/System32/Config/SYSTEM")
file_data = file_obj.read_random(0,file_obj.info.meta.size)
reg = Registry.Registry(FileLikeDummy(file_data))
print(reg.hive_name())
```

Other then that I think you have a few errors, reasigning and overwriting data and using incorrect variable names (?), here is an attempt at fix:
```Python
file_obj = filesystem_obj.open("/Windows/System32/Config/SYSTEM")
file_data = file_obj.read_random(0,file_obj.info.meta.size)
strio = StringIO.StringIO()
strio.write(file_data)
reg = Registry.Registry(strio)
print(reg.hive_name())
```

Don't know if this works, also see that use of the dummy class is based on your code and assumes that it gets file_data that is valid for python-registry as a buffer object.

**Comment by NiKiZe** [comment]
@hiddenillusion where you able to come up with a solution?

**Comment by msuhanov** [comment]
@hiddenillusion, you need to seek to the beginning of the _file_data_:
<pre>
>>> import StringIO
>>> buf = StringIO.StringIO()
>>> buf.write('1234567890')
>>> buf.tell()
10
>>> buf.read()
''
>>> buf.seek(0)
>>> buf.read()
'1234567890'
</pre>

**Comment by hiddenillusion** [comment]
@msuhanov thanks for that - didn't realize StringIO's position was set to the end of the buf after performing the `write()`.

@williballenthin - this can be closed.
