### ISSUE TITLE
Can't read "Current Version\\Run".

### ISSUE THREAD

**Issue by MariasStory** [williballenthin/python-registry#69]
Hi,
I am somewhat confused.
I downloaded the NTUSER.DAT file and put it in hives sub-directory.
Now I am trying to do:

> f = open("hives/NTUSER.DAT", "rb")
> reg = Registry.Registry(f)
> 
> key = reg.open("SOFTWARE\\Microsoft\\Windows\\Current Version\\Run")

This gives me:

> Traceback (most recent call last):
>   File "C:\Users\c5211757\Documents\Programming\pythonRegistry\getRegValue1.py", line 10, in <module>
>     key = reg.open("SOFTWARE\\Microsoft\\Windows\\Current Version\\Run")
>   File "C:\Users\c5211757\Documents\Programming\pythonRegistry\Registry\Registry.py", line 290, in open
>     return RegistryKey(self._regf.first_key()).find_key(path)
>   File "C:\Users\c5211757\Documents\Programming\pythonRegistry\Registry\Registry.py", line 254, in find_key
>     return self.subkey(immediate).find_key(future)
>   File "C:\Users\c5211757\Documents\Programming\pythonRegistry\Registry\Registry.py", line 217, in subkey
>     for k in self._nkrecord.subkey_list().keys():
>   File "C:\Users\c5211757\Documents\Programming\pythonRegistry\Registry\RegistryParse.py", line 900, in keys
>     yield NKRecord(self._buf, d.data_offset(), self)
>   File "C:\Users\c5211757\Documents\Programming\pythonRegistry\Registry\RegistryParse.py", line 999, in __init__
>     raise ParseException("Invalid NK Record ID")
> Registry.RegistryParse.ParseException: Registry Parse Exception(Invalid NK Record ID)
> 

What am I doing wrong?

**Comment by williballenthin** [comment]
> I downloaded the NTUSER.DAT

from where did you download this hive file?

the exception seems to suggest that the hive is corrupt. if the hive is public, then i can try to reproduce the issue.

**Comment by MariasStory** [comment]
Hi @williballenthin . I got it working. The problem was in a broken NTUSER.DAT as you suggested. Thanks.

**Comment by williballenthin** [comment]
this library doesn't do any special processing of spaces. it uses the `\` character to split the registry path components, but thats about it. so if there's a subkey with an embedded space, you should be able to include it in your path without any issue.

feel free to open another issue if you're having any more trouble, and i'll be happy to help.
