### ISSUE TITLE
[feature request] explaination to do a basic search replace on key/value/name traversing all the registry

### ISSUE THREAD

**Issue by WiliTest** [williballenthin/python-registry#78]
I'm a basic python user searching for a way to find and replace (everywhere in the registry) "old" by "new" (in name, key, value, even in the protected keys). 

It would be nice to add to your documentation basic explaination (for basic user)  

(Python 3.6, windows 7).

**Comment by williballenthin** [comment]
hey @WiliTest 

thanks for submitting this feedback! unfortunately, it sounds like `python-registry` probably will not work for your needs. this library only supports reading data, and cannot write to registry files. you might find the `_winreg` module (in the python standard library) more suitable.
