### ISSUE TITLE
It's not clear that this doesn't support Windows 95-style registry files

### ISSUE THREAD

**Issue by dcoshea** [williballenthin/python-registry#83]
`README.MD` doesn't explicitly say one way or the other whether this code only supports Windows NT-style registry files, or if it also supports Windows 95-style registry files.

I found that it doesn't support Windows 95-style files as at a002bb3:

      File "[...]/python2.7/site-packages/Registry/RegistryParse.py", line 295, in __init__
        raise ParseException("Invalid REGF ID")
    Registry.RegistryParse.ParseException: Registry Parse Exception (Invalid REGF ID)

This was raised because the signature wasn't `0x66676572`, which appears to be a Windows NT-specific signature based on a quick skim through `documentation/WinReg.txt`.

It would be nice if this was mentioned explicitly in `README.MD`.

**Comment by williballenthin** [comment]
hey @dcoshea 

Good point! I've updated the readme to make this more explicit. c6e75fb2dce809ceba4590cd5a82ef4ac00e4abe
