### ISSUE TITLE
List comprehension syntax error in usage

### ISSUE THREAD

**Issue by nicholaswallen** [williballenthin/python-registry#87]
In the usage examples to "Find a key and print all string values" i believe there is a syntax error in the list comprehension.

for value in [v for v key.values() \
                   if v.value_type() == Registry.RegSZ or \
                      v.value_type() == Registry.RegExpandSZ]:

should be

for value in [v for v **in** key.values() \
                   if v.value_type() == Registry.RegSZ or \
                      v.value_type() == Registry.RegExpandSZ]:

**Comment by williballenthin** [comment]
good catch, thanks!

fixed in readme
