### ISSUE TITLE
Provide new release?

### ISSUE THREAD

**Issue by mika** [williballenthin/python-registry#91]
The latest release (1.2.0) dates back to 2015-12-22, while there have been quite some commits since then. Is there any chance we might get a new release? :)

Thanks for python-registry!

**Comment by williballenthin** [comment]
1.3.0 tagged and pushed to pypi! 

https://github.com/williballenthin/python-registry/releases/tag/1.3.0

**Comment by mika** [comment]
@williballenthin thank you! :+1:
