### ISSUE TITLE
Website doesn't work

### ISSUE THREAD

**Issue by mgedmin** [williballenthin/python-registry#92]
http://www.williballenthin.com/registry/ is giving me a 404 Not Found error.

**Comment by williballenthin** [comment]
this GitHub repository is the canonical location for python-registry going forward

**Comment by mgedmin** [comment]
I've created a PR to update the URL in setup.py to point to GitHub.

I would also suggest changing the URL at the top of the GitHub page to point to https://pypi.org/project/python-registry/
