### ISSUE TITLE
cannot read HKEY_CURRENT_USER Invalid REGF ID

### ISSUE THREAD

**Issue by GrigorDimitrov** [williballenthin/python-registry#94]

**Comment by williballenthin** [comment]
there is not enough detail in this issue to triage any bug. please provide additional information, potentially including the source detail, to help me help you.

this message means that the file you're inspecting doesn't have the magic header associated with a registry hive.

**Comment by GrigorDimitrov** [comment]
The reason this error appears is because I didn't export the registry hive correctly as a 'Registry Hive File'. It was my fault.

**Comment by williballenthin** [comment]
👍 thanks for the update
